Ds 1590 ElasticSearch incremental loads
panoplyio/source-elasticsearch pull request #10
Opened 2021-01-16 16:36 UTC by arsen-senkivskyy

Added incremental key support

2021-01-18 22:59 UTC, ilia-panoply requested changes

2021-01-18 22:59 UTC, ilia-panoply commented on setup.py
> +    version="1.1.1",
@arsen-senkivskyy you are adding a new feature, please bump the minor version instead of patch

2021-01-20 07:44 UTC, dsoloh approved these changes

2021-01-20 08:27 UTC, ilia-panoply approved these changes

2021-01-20 08:59 UTC, merged