Added GitHub actions
panoplyio/source-elasticsearch pull request #12
Opened 2021-01-26 13:20 UTC by arsen-senkivskyy

Added GitHub actions, removed Travis CI, fixed linter warnings.

2021-01-26 13:44 UTC, ilia-panoply approved these changes

2021-01-26 13:54 UTC, dsoloh requested changes

2021-01-26 13:54 UTC, dsoloh commented on .github/workflows/CI_check.yml
> +        pycodestyle --format=pylint --count .
Please, add release step, you can take a look at the example [here](https://github.com/panoplyio/source-googledrive/blob/master/.github/workflows/on-pull-request.yml

2021-01-27 11:47 UTC, dsoloh approved these changes

2021-01-27 12:17 UTC, merged